version: "3.9"
services:

  crud_service:
    build: ./microservices/CrudMovieService
    ports:
      - "3000:3000"
    networks:
      - serviceNetwork

  # review_service:
  #   build: ./microservices/ReviewService
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - serviceNetwork

  # search_service:
  #   build: ./microservices/SearchService
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - serviceNetwork

  # auth_service:
  #   build: ./microservices/AuthService
  #   ports:
  #     - "3003:3003"
  #   networks:
  #     - serviceNetwork


networks:
  serviceNetwork:
