version: "3.9"
services:

  crud_service:
    build: ./microservices/CrudMovieService
    ports:
      - "3000:3000"
    networks:
      - serviceNetwork
      - baseNetwork

  client:
    build: ./frontend
    ports:
      - "4000:3000"
    networks:
      - baseNetwork


networks:
  serviceNetwork:
  baseNetwork: 